#!/bin/bash
# description: prospector 
# processname: twistd
# chkconfig: 2345 55 25

TWISTD=/home/jkoelker/devenvs/prospector/bin/twistd
MODULE=prospector
PIDFILE=/home/jkoelker/devenvs/prospector/var/run/${MODULE}.pid
LOGFILE=/home/jkoelker/devenvs/prospector/var/log/${MODULE}.log
CONFIG=/home/jkoelker/devenvs/prospector/prospector.conf

if [ "${1}" = 'start' ]; then
    RUNPID=`pgrep -f ${TWISTD} 2>/dev/null`
    if [ "$?" -ne 0 ]; then
        RUNPID=-1
    fi
    RECPID=`cat ${PIDFILE} 2>/dev/null`
    if [ "$?" -ne 0 ]; then
        RECPID=-2
    fi
    if [ "${RUNPID}" -eq "${RECPID}" ]; then
        echo "${MODULE} is already running!"
    else
        ${TWISTD} --pidfile=${PIDFILE} --logfile=${LOGFILE} ${MODULE} -f ${CONFIG}
    fi
elif [ "${1}" = 'stop' ]; then
    kill -s SIGTERM `cat ${PIDFILE} 2>/dev/null` 2>/dev/null
else
    echo "usage $0 [start|stop]"
fi

